config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :goaltemplates
  resources :days
  devise_for :users
  get "about" => "pages#about"
  root "days#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :timeoutable, :rememberable, :trackable, :validatable
end

app/models/day.rb
class Day < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
    validates :image, presence: true
end

app/models/goaltemplate.rb
class Goaltemplate < ActiveRecord::Base
	belongs_to :user
	default_scope { order('area') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
   def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
   devise_parameter_sanitizer.for(:account_update) << :nickname
 end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
before_action :current_user, only: [:edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all.order("created_at DESC").paginate(:page => params[:page],:per_page=>4)
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = current_user.days.build
    #Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
  respond_to do |format|
      @day = current_user.days.build(day_params) # Day.new(day_params)
    if @day.save
      format.html { redirect_to @day, notice: 'Day was added.' }
     format.json { render :show, status: :created, location: @day }
    else
      render :new
    end
  end

#    respond_to do |format|
#      if @day.save
#        format.html { redirect_to @day, notice: 'Day was successfully created.' }
#        format.json { render :show, status: :created, location: @day }
#      else
#        format.html { render :new }
#        format.json { render json: @day.errors, status: :unprocessable_entity }
#      end
#    end

  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html {redirect_to @day, notice: 'Day was updated'}
        # format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }

      else
        format.html { render :edit }
        # format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:day,:goal, :good, :bad, :actions, :regret,:image)
    end
end

app/controllers/goaltemplates_controller.rb
class GoaltemplatesController < ApplicationController
  before_action :set_goaltemplate, only: [:show, :edit, :update, :destroy]

  # GET /goaltemplates
  # GET /goaltemplates.json
  def index
    @goaltemplates = Goaltemplate.all
  end

  # GET /goaltemplates/1
  # GET /goaltemplates/1.json
  def show
  end

  # GET /goaltemplates/new
  def new
    @goaltemplate = Goaltemplate.new
  end

  # GET /goaltemplates/1/edit
  def edit
  end

  # POST /goaltemplates
  # POST /goaltemplates.json
  def create
    @goaltemplate = Goaltemplate.new(goaltemplate_params)

    respond_to do |format|
      if @goaltemplate.save
        format.html { redirect_to @goaltemplate, notice: 'Goaltemplate was successfully created.' }
        format.json { render :show, status: :created, location: @goaltemplate }
      else
        format.html { render :new }
        format.json { render json: @goaltemplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goaltemplates/1
  # PATCH/PUT /goaltemplates/1.json
  def update
    respond_to do |format|
      if @goaltemplate.update(goaltemplate_params)
        format.html { redirect_to @goaltemplate, notice: 'Goaltemplate was successfully updated.' }
        format.json { render :show, status: :ok, location: @goaltemplate }
      else
        format.html { render :edit }
        format.json { render json: @goaltemplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goaltemplates/1
  # DELETE /goaltemplates/1.json
  def destroy
    @goaltemplate.destroy
    respond_to do |format|
      format.html { redirect_to goaltemplates_url, notice: 'Goaltemplate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goaltemplate
      @goaltemplate = Goaltemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goaltemplate_params
      params.require(:goaltemplate).permit(:goal, :area)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/goaltemplates_helper.rb
module GoaltemplatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    On
    <%= f.date_field :day , class:"form-control"%>
  </div>

  <div class="form-group">
    The primary goal was
    <%= f.collection_select( :goal, Goaltemplate.order(:goal),:goal,:goal, {include_blank: true} , {class:"form-control",width:"50%"} )  %> 
     <%= link_to 'New Goal', new_goaltemplate_path %>
   
  </div>
  <div class="form-group">
    What went well?<br>
    <%= f.text_field :good, class:"form-control" %>
  </div>
  <div class="form-group">
    What didn't go well<br>
    <%= f.text_field :bad, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :actions %><br>
    <%= f.text_area :actions , rows:5 , class:"form-control"%>
  </div>
  <div class="form-group">
    The regret that came to mind was<br>
    <%= f.text_field :regret , class:"form-control"%>
  </div>
  <div class="form-group">
<%= f.label :image %>
<%= f.file_field :image, class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/days/edit.html.erb
<h3>Tell me about your day</h3>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<p id="notice"><%= notice %></p>
<%= link_to "Hello "+current_user.nickname.to_s,edit_user_registration_path unless !user_signed_in? %>

<h1>Days</h1>


<div id="days" class="transitions-enabled">
    <%  
    @days.each do |day| %>
    <div class="box panel panel-default">
    <%= link_to day.day,day %> Focus on <%= day.goal %> 
      <%= link_to image_tag(day.image.url(:medium)),day if !day.image.blank?%><br>
      <div class="panel-body">
        <%= day.good %>
         <%= day.bad %>
        <%= day.actions %>
        <%= day.regret if !day.regret.blank?%> 
       <!-- <%= link_to 'Show', day %> -->
        <% if day.user == current_user %>
          <div class="actions">
          <%= link_to edit_day_path(day) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to day, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        
          </div>
        <% end %>

      </div>
      </div>
    <% end %>
</div>

<br>

<div class="center">
<%= will_paginate @days, renderer: BootstrapPagination::Rails %>
</div>

app/views/days/new.html.erb
<h1>New Day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<%= link_to 'Back',days_path %>
<div class="row">
 <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">

<p id="notice"><%= notice %></p>
On <%= @day.day %>
<p>
I wanted to focus on <%= @day.goal %>
</p>
</div>
<div class="panel-body">
<p>
  <strong>Good:</strong>
  <%= @day.good %>
</p>

<p>
  <strong>Bad:</strong>
  <%= @day.bad %>
</p>

<p>
  <strong>Actions:</strong>
  <%= @day.actions %>
</p>

<p>
  <strong>Regret:</strong>
  <%= @day.regret %>
</p>

<%= image_tag @day.image.url(:medium) if !@day.image.blank? %>
<% if @day.user == current_user %>
<%= link_to 'Edit', edit_day_path(@day) %>
<% end %>
<%= link_to edit_day_path(@day) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
</div>
</div>
</div>
</div>

app/views/goaltemplates/_form.html.erb
<%= form_for(@goaltemplate) do |f| %>
  <% if @goaltemplate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goaltemplate.errors.count, "error") %> prohibited this goaltemplate from being saved:</h2>

      <ul>
      <% @goaltemplate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :goal %><br>
    <%= f.text_field :goal, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :area %><br>

<%= f.select :area, ["Business","Play","Career","Home","Personal","Health/Wellness"], {},
  class:"form-control" %>
    
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/goaltemplates/edit.html.erb
<h1>Editing Goaltemplate</h1>

<%= render 'form' %>

<%= link_to 'Show', @goaltemplate %> |
<%= link_to 'Back', goaltemplates_path %>

app/views/goaltemplates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>


    <% @goaltemplates.each do |goaltemplate| %>
    <div class="box panel">
      <h2><%= goaltemplate.area %></h2>
        <p><%= goaltemplate.goal %></p>
        <%= link_to 'Show', goaltemplate %>
        <%= link_to 'Edit', edit_goaltemplate_path(goaltemplate) %>
        <%= link_to 'Destroy', goaltemplate, method: :delete, data: { confirm: 'Are you sure?' } %>
    
      </div>
    <% end %>


<br>

<%= link_to 'New Goal', new_goaltemplate_path %>

app/views/goaltemplates/new.html.erb
<h1>New Goaltemplate</h1>

<%= render 'form' %>

<%= link_to 'Back', goaltemplates_path %>

app/views/goaltemplates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @goaltemplate.goal %>
</p>

<p>
  <strong>Area:</strong>
  <%= @goaltemplate.area %>
</p>

<%= link_to 'Edit', edit_goaltemplate_path(@goaltemplate) %> |
<%= link_to 'Back', goaltemplates_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "HappiGoals", root_path ,class:"navbar-brand"%>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to 'New Day', new_day_path %></li>
    <li><%= link_to 'Days',days_path %></li>
    <li><%= link_to 'Goals',goaltemplates_path %></li>
    <li>
            <%= link_to new_goaltemplate_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Goal
            <% end %>
          </li>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <%if user_signed_in? %>
      <li><%= link_to "Log out",destroy_user_session_path,method: :delete %></li>
      <%end%> 
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Happigoals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>
</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
<h1>Welcome to my app!</h1>
 <p>
       <%= link_to "Log in", new_user_session_path , class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
  </p>    


</div><div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>This is my information Page</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome to my app!</h1>
<% if user_signed_in? %>
 <%else%> 
 <p>
       <%= link_to "Log in", new_user_session_path , class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
  </p>    
  <% end %>

</div><div>